# PostgreSQL R2DBC Configuration
spring:
  r2dbc:
    url: ${R2DBC_URL}
    username: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 10m
      max-lifetime: 30m
  flyway:
    enabled: false
    locations: classpath:db/migration
    url: ${FLYWAY_URL}
    password: ${FLYWAY_PASSWORD}
    user: ${FLYWAY_USERNAME}
  data:
    r2dbc:
      log-level: debug

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server/issuer
          jwk-set-uri: http://auth-server/.well-known/jwks.json

  webflux:
    base-path: /api
    codecs:
      max-in-memory-size: 16MB

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE

