
spring:
  webflux:
    base-path: /api
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/smart_home
    username: postgres
    password: postgres
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 10m
      max-lifetime: 30m
  flyway:
    enabled: false
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/smart_home
    password: postgres
    user: postgres
  data:
    r2dbc:
      log-level: debug

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server/issuer
          jwk-set-uri: http://auth-server/.well-known/jwks.json

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE